	function load_images()
{
	//player movement
	game.load.image('w_up_0', 'anim_player/W_UP_0.png');
	game.load.image('w_up_1', 'anim_player/W_UP_1.png');
	game.load.image('w_up_2', 'anim_player/W_UP_2.png');
	game.load.image('explo-0-mid', 'anim_bombs/MID_EXPLO_3.png');
	game.load.image('explo-1-mid', 'anim_bombs/MID_EXPLO_2.png');
	game.load.image('explo-2-mid', 'anim_bombs/MID_EXPLO_1.png');
	game.load.image('explo-3-mid', 'anim_bombs/MID_EXPLO_0.png');
	game.load.image('explo-0-midleft', 'anim_bombs/M_LEFT_EXPLO_3.png');
	game.load.image('explo-1-midleft', 'anim_bombs/M_LEFT_EXPLO_2.png');
	game.load.image('explo-2-midleft', 'anim_bombs/M_LEFT_EXPLO_1.png');
	game.load.image('explo-3-midleft', 'anim_bombs/M_LEFT_EXPLO_0.png');
	game.load.image('explo-0-maxleft', 'anim_bombs/T_LEFT_EXPLO_3.png');
	game.load.image('explo-1-maxleft', 'anim_bombs/T_LEFT_EXPLO_2.png');
	game.load.image('explo-2-maxleft', 'anim_bombs/T_LEFT_EXPLO_1.png');
	game.load.image('explo-3-maxleft', 'anim_bombs/T_LEFT_EXPLO_0.png');
	game.load.image('explo-0-midtop', 'anim_bombs/M_UP_EXPLO_3.png');
	game.load.image('explo-1-midtop', 'anim_bombs/M_UP_EXPLO_2.png');
	game.load.image('explo-2-midtop', 'anim_bombs/M_UP_EXPLO_1.png');
	game.load.image('explo-3-midtop', 'anim_bombs/M_UP_EXPLO_0.png');
	game.load.image('explo-0-maxtop', 'anim_bombs/T_UP_EXPLO_3.png');
	game.load.image('explo-1-maxtop', 'anim_bombs/T_UP_EXPLO_2.png');
	game.load.image('explo-2-maxtop', 'anim_bombs/T_UP_EXPLO_1.png');
	game.load.image('explo-3-maxtop', 'anim_bombs/T_UP_EXPLO_0.png');
	game.load.image('explo-0-middown', 'anim_bombs/M_DOWN_EXPLO_3.png');
	game.load.image('explo-1-middown', 'anim_bombs/M_DOWN_EXPLO_2.png');
	game.load.image('explo-2-middown', 'anim_bombs/M_DOWN_EXPLO_1.png');
	game.load.image('explo-3-middown', 'anim_bombs/M_DOWN_EXPLO_0.png');
	game.load.image('explo-0-maxdown', 'anim_bombs/T_DOWN_EXPLO_3.png');
	game.load.image('explo-1-maxdown', 'anim_bombs/T_DOWN_EXPLO_2.png');
	game.load.image('explo-2-maxdown', 'anim_bombs/T_DOWN_EXPLO_1.png');
	game.load.image('explo-3-maxdown', 'anim_bombs/T_DOWN_EXPLO_0.png');
	game.load.image('explo-0-midright', 'anim_bombs/M_RIGHT_EXPLO_3.png');
	game.load.image('explo-1-midright', 'anim_bombs/M_RIGHT_EXPLO_2.png');
	game.load.image('explo-2-midright', 'anim_bombs/M_RIGHT_EXPLO_1.png');
	game.load.image('explo-3-midright', 'anim_bombs/M_RIGHT_EXPLO_0.png');
	game.load.image('explo-0-maxright', 'anim_bombs/T_RIGHT_EXPLO_3.png');
	game.load.image('explo-1-maxright', 'anim_bombs/T_RIGHT_EXPLO_2.png');
	game.load.image('explo-2-maxright', 'anim_bombs/T_RIGHT_EXPLO_1.png');
	game.load.image('explo-3-maxright', 'anim_bombs/T_RIGHT_EXPLO_0.png');
}
